### ISSUE TITLE
cherrypy._cperror.NotFound: (404, "The path '/' was not found.")

### ISSUE THREAD

**Issue by arne-cl** [proycon/flat#10]
Hallo Maarten,

I was curious and wanted to try FLAT. After I started ``foliadocserve.py`` and went to ``http://localhost:8080/``,

```python
~/repos/flat $ python3 foliadocserve.py --workdir /tmp
[12/Feb/2015:15:58:42] ENGINE Listening for SIGHUP.
[12/Feb/2015:15:58:42] ENGINE Listening for SIGTERM.
[12/Feb/2015:15:58:42] ENGINE Listening for SIGUSR1.
[12/Feb/2015:15:58:42] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[12/Feb/2015:15:58:42] ENGINE Started monitor thread '_TimeoutMonitor'.
[12/Feb/2015:15:58:42] ENGINE Started monitor thread 'Autoreloader'.
[12/Feb/2015:15:58:42] ENGINE Serving on http://0.0.0.0:8080
[12/Feb/2015:15:58:42] ENGINE Bus STARTED
```

I got the following respose:

```python
404 Not Found

The path '/' was not found.

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/_cperror.py", line 411, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/' was not found.")

Powered by CherryPy 3.6.0
```

I'm running ``Python 3.2.3``, if that makes any difference.

Best,
Arne

**Comment by proycon** [comment]
That's correct, there's nothing at the root there. The document server has no user front-end, it's a back-end FLAT communicates with. Try setting up FLAT itself if you want to give it a try.
