### ISSUE TITLE
Upload fails 

### ISSUE THREAD

**Issue by proycon** [proycon/flat#14]
/var/www2/flat/live/repo/flat/flat/views.py:393:  string indices must be integers

```
Variable 	Value
namespace 	

u'proycon'

request 	

"<WSGIRequest\npath:/upload/,\nGET:<QueryDict: {}>,\nPOST:<QueryDict: {u'csrfmiddlewaretoken': [u'5SZbS2XRCLwi9viv6HStJQSumWW1uYQh'], u'namespace': [u'proycon']}>,\nCOOKIES:{'_ga': 'GA1.2.2015558836.1455801865',\n 'csrftoken': '5SZbS2XRCLwi9viv6HStJQSumWW1uYQh',\n 'sessionid': 'yrqjbffstoeu4dcc60ql7iby1tnpes7w'},\nMETA:{'CONTENT_LENGTH': '1562',\n 'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------10697876931225869966504688403',\n 'CONTEXT_DOCUMENT_ROOT': '/var/www2/flat/live/htdocs',\n 'CONTEXT_PREFIX': '',\n u'CSRF_COOKIE': u'5SZbS2XRCLwi9viv6HStJQSumWW1uYQh',\n 'DOCUMENT_ROOT': '/var/www2/flat/live/htdocs',\n 'GATEWAY_INTERFACE': 'CGI/1.1',\n 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',\n 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',\n 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',\n 'HTTP_CONNECTION': 'keep-alive',\n 'HTTP_COOKIE': '_ga=GA1.2.2015558836.1455801865; csrftoken=5SZbS2XRCLwi9viv6HStJQSumWW1uYQh; sessionid=yrqjbffstoeu4dcc60ql7iby1tnpes7w',\n 'HTTP_HOST': 'flat.science.ru.nl',\n 'HTTP_REFERER': 'http://flat.science.ru.nl/index/proycon',\n 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0',\n 'PATH_INFO': u'/upload/',\n 'PATH_TRANSLATED': '/var/www2/flat/live/repo/flat/spitfire.wsgi/upload/',\n 'QUERY_STRING': '',\n 'REMOTE_ADDR': '131.174.133.230',\n 'REMOTE_PORT': '58962',\n 'REQUEST_METHOD': 'POST',\n 'REQUEST_SCHEME': 'http',\n 'REQUEST_URI': '/upload/',\n 'SCRIPT_FILENAME': '/var/www2/flat/live/repo/flat/spitfire.wsgi',\n 'SCRIPT_NAME': u'',\n 'SERVER_ADDR': '131.174.16.30',\n 'SERVER_ADMIN': '[no address given]',\n 'SERVER_NAME': 'flat.science.ru.nl',\n 'SERVER_PORT': '80',\n 'SERVER_PROTOCOL': 'HTTP/1.1',\n 'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at flat.science.ru.nl Port 80</address>\\n',\n 'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',\n 'mod_wsgi.application_group': 'flat.science.ru.nl|',\n 'mod_wsgi.callable_object': 'application',\n 'mod_wsgi.enable_sendfile': '0',\n 'mod_wsgi.handler_script': '',\n 'mod_wsgi.input_chunked': '0',\n 'mod_wsgi.listener_host': '131.174.16.30',\n 'mod_wsgi.listener_port': '80',\n 'mod_wsgi.process_group': 'flat',\n 'mod_wsgi.queue_start': '1458215635469977',\n 'mod_wsgi.request_handler': 'wsgi-script',\n 'mod_wsgi.script_reloading': '1',\n 'mod_wsgi.version': (3, 4),\n 'wsgi.errors': <mod_wsgi.Log object at 0x7ff27fef4030>,\n 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7ff27feb25d0>,\n 'wsgi.input': <mod_wsgi.Input object at 0x7ff27fef46b0>,\n 'wsgi.multiprocess': False,\n 'wsgi.multithread': True,\n 'wsgi.run_once': False,\n 'wsgi.url_scheme': 'http',\n 'wsgi.version': (1, 0)}>"

response 	

u'<!DOCTYPE html PUBLIC\n"-//W3C//DTD XHTML 1.0 Transitional//EN"\n"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>\n    <title>500 Internal Server Error</title>\n    <style type="text/css">\n    #powered_by {\n        margin-top: 20px;\n        border-top: 2px solid black;\n        font-style: italic;\n    }\n\n    #traceback {\n        color: red;\n    }\n    </style>\n</head>\n    <body>\n        <h2>500 Internal Server Error</h2>\n        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>\n        <pre id="traceback"></pre>\n    <div id="powered_by">\n      <span>\n        Powered by <a href="http://www.cherrypy.org">CherryPy 3.8.0</a>\n      </span>\n    </div>\n    </body>\n</html>\n'
```

**Comment by proycon** [comment]
Caused by docserve:

```
Traceback (most recent call last):
  File "/scratch2/www/lamachine/lib/python3.4/site-packages/CherryPy-3.8.0-py3.4.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/scratch2/www/lamachine/lib/python3.4/site-packages/CherryPy-3.8.0-py3.4.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/scratch2/www/lamachine/lib/python3.4/site-packages/CherryPy-3.8.0-py3.4.egg/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/scratch2/www/lamachine/lib/python3.4/site-packages/foliadocserve-0.3.3-py3.4.egg/foliadocserve/foliadocserve.py", line 731, in upload
    self.docstore.save((namespace,doc.id), "Initial upload")
  File "/scratch2/www/lamachine/lib/python3.4/site-packages/foliadocserve-0.3.3-py3.4.egg/foliadocserve/foliadocserve.py", line 230, in save
    elif doc.changed:
AttributeError: 'Document' object has no attribute 'changed'
```

**Comment by proycon** [comment]
Fixed
