### ISSUE TITLE
Flat Problem with Folia doc server after upgrading to current release

### ISSUE THREAD

**Issue by languagerecipes** [proycon/flat#49]
Hi, 

after upgrading to current release I get the following error message:
Any idea what I should do to resolve the issue?

```
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'settings'

```

**Comment by proycon** [comment]
That does not look like an error from ``foliadocserve``. It refers to django so is an error from FLAT itself. What command produced this?

**Comment by languagerecipes** [comment]
jusr trying to start the document server, the command noted in the user
guide

**Comment by proycon** [comment]
I think you probably tried the wrong command  (starting the FLAT development server), the folia document server does not use django and is started using: ``foliadocserve -d /path/to/document/root -p 8080``, as the instructions in the README say.

**Comment by languagerecipes** [comment]
true, the command was wrong!
